language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
# install dependencies
#install:
#  - pip install -r requirements.txt
#before_script:
#  - rm ./handlers/ytdl.py
# command to run tests
script: python main.py --test --update --skip_pauses --username=$username --password=$password --c_id=$client_id --c_secret=$client_secret --agent="TestUpdaterAgent"
notifications:
  email: false
  webhooks: 
    urls:
      - https://hook.rofl.wtf/
    on_success: change
    on_failure: change
    on_start: change
    on_cancel: never
    on_error: change
