language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
- pip install coveralls
- pip install pycryptodome
- python ./classes/tools/encryptor.py decrypt ./tests/test-settings.json.enc ./tests/test-settings.json
script:
- coverage run main.py --test --update_only --skip_pauses
- coverage run main.py --test --skip_pauses
after_script:
- COVERALLS_PARALLEL=true coveralls
notifications:
  email: false
  webhooks:
    urls:
    - https://hook.rofl.wtf/
    on_success: change
    on_failure: change
    on_start: change
    on_cancel: never
    on_error: change
